alfa_system_interfaces/TaskContext context
alfa_task_interfaces/PlaceTarget[] targets
string motion_profile_id
string placement_profile_id
string grip_profile_id
string expected_gate_owner
uint64 expected_gate_token
---
alfa_task_interfaces/PlaceOutcome[] outcomes
uint8 overall_verification_level
alfa_system_interfaces/ErrorInfo error
---
string stage
float32 progress_0_to_1
