# Copyright (c) 2025 b»robotized group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ros2_control controllers for the v5 proxy dual six-axis arms.

controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    base_position_controller:
      type: forward_command_controller/ForwardCommandController

    left_v5_arm_position_controller:
      type: forward_command_controller/ForwardCommandController

    right_v5_arm_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    all_position_controller:
      type: forward_command_controller/ForwardCommandController

base_position_controller:
  ros__parameters:
    joints:
      - pitch
      - turn
      - updown
    interface_name: position

left_v5_arm_position_controller:
  ros__parameters:
    joints:
      - left_v5_joint1
      - left_v5_joint2
      - left_v5_joint3
      - left_v5_joint4
      - left_v5_joint5
      - left_v5_joint6
    interface_name: position

right_v5_arm_position_controller:
  ros__parameters:
    joints:
      - right_v5_joint1
      - right_v5_joint2
      - right_v5_joint3
      - right_v5_joint4
      - right_v5_joint5
      - right_v5_joint6
    interface_name: position

forward_velocity_controller:
  ros__parameters:
    joints:
      - left_back
      - left_forward
      - right_back
      - right_forward
    interface_name: velocity

all_position_controller:
  ros__parameters:
    joints:
      - pitch
      - turn
      - updown
      - left_v5_joint1
      - left_v5_joint2
      - left_v5_joint3
      - left_v5_joint4
      - left_v5_joint5
      - left_v5_joint6
      - right_v5_joint1
      - right_v5_joint2
      - right_v5_joint3
      - right_v5_joint4
      - right_v5_joint5
      - right_v5_joint6
    interface_name: position
