# 滑块测试配置 - v5 proxy all-position controller.

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    v5_slider_controller:
      type: forward_command_controller/ForwardCommandController

v5_slider_controller:
  ros__parameters:
    joints:
      - pitch
      - turn
      - updown
      - left_v5_joint1
      - left_v5_joint2
      - left_v5_joint3
      - left_v5_joint4
      - left_v5_joint5
      - left_v5_joint6
      - right_v5_joint1
      - right_v5_joint2
      - right_v5_joint3
      - right_v5_joint4
      - right_v5_joint5
      - right_v5_joint6
    interface_name: position
