"""Offsets for each 32-WORD MB_CMD/MB_STS axis block."""

from enum import IntEnum


class ControlWord:
    CLEAR = 0x0000
    ENABLE = 0x0001
    RESET_FAULT = 0x0002
    MOVE_ABS = 0x0004
    STOP = 0x0008
    SET_ZERO = 0x0010
    RETURN_ZERO = 0x0020
    STEP_PLUS = 0x0040
    STEP_MINUS = 0x0080
    EMERGENCY_STOP = 0x0100
    DISABLE = 0x0200
    RESET_EMERGENCY = 0x0400

    ENABLE_MOVE_ABS = ENABLE | MOVE_ABS
    ENABLE_STOP = ENABLE | STOP
    ENABLE_EMERGENCY_STOP = ENABLE | EMERGENCY_STOP
    ENABLE_RESET_EMERGENCY = ENABLE | RESET_EMERGENCY
    ENABLE_RESET_FAULT = ENABLE | RESET_FAULT


class AxisCmdOffset(IntEnum):
    CONTROL_WORD = 0
    COMMAND_ID = 1
    TARGET_SINGLE_POS_LOW = 2
    TARGET_SINGLE_POS_HIGH = 3
    VELOCITY = 4
    ACC = 5
    DEC = 6
    STEP_DEG = 7
    RESERVED_8 = 8
    EMERGENCY_DEC = 9


class AxisStsOffset(IntEnum):
    STATUS_WORD = 0
    ACK_COMMAND_ID = 1
    ERROR_CODE = 2
    RESERVED_3 = 3
    RESERVED_4 = 4
    FEEDBACK_POS_LOW = 5
    FEEDBACK_POS_HIGH = 6
    FEEDBACK_SINGLE_LOW = 7
    FEEDBACK_SINGLE_HIGH = 8
    LAST_TARGET_LOW = 9
    LAST_TARGET_HIGH = 10


class SysOffset(IntEnum):
    PROTOCOL_MODE = 0
    ACTIVE_AXIS_COUNT = 1
    MAX_AXIS_CAPACITY = 2
    AXIS_BLOCK_SIZE = 3
    POSITION_SCALE = 4
    SPEED_SCALE = 5
    CMD_BASE_MW = 6
    STS_BASE_MW = 7
    SYS_BASE_MW = 8
    HEARTBEAT = 9
