uint8 EXECUTION_STAGE_UNSPECIFIED=0
uint8 EXECUTION_STAGE_CAMERA_VIEW=1
uint8 EXECUTION_STAGE_PREGRASP=2
uint8 EXECUTION_STAGE_APPROACH=3
uint8 EXECUTION_STAGE_PLACE=4
uint8 EXECUTION_STAGE_HOME=5

uint8 execution_stage
alfa_motion_interfaces/DualArmPoseTargets targets
---
string diagnostic
---
uint8 MOTION_STATE_UNSPECIFIED=0
uint8 MOTION_STATE_PLANNING=1
uint8 MOTION_STATE_EXECUTING=2
uint8 MOTION_STATE_SETTLING=3

uint8 motion_state
