# Default initial positions for alfa_robot v5 proxy model

initial_positions:
  pitch: 0
  turn: 0
  updown: 0
  left_v5_joint1: 0
  left_v5_joint2: 0
  left_v5_joint3: 0
  left_v5_joint4: 0
  left_v5_joint5: 0
  left_v5_joint6: 0
  right_v5_joint1: 0
  right_v5_joint2: 0
  right_v5_joint3: 0
  right_v5_joint4: 0
  right_v5_joint5: 0
  right_v5_joint6: 0
