# ROS2 controller configuration
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    updown_controller:
      type: forward_command_controller/ForwardCommandController

    pitch_controller:
      type: forward_command_controller/ForwardCommandController

    turn_controller:
      type: forward_command_controller/ForwardCommandController

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50.0

joint_trajectory_controller:
  ros__parameters:
    joints:
      - leftjoint1
      - leftjoint2
      - leftjoint3
      - leftjoint4
      - leftjoint5
      - leftjoint6
      - rightjoint1
      - rightjoint2
      - rightjoint3
      - rightjoint4
      - rightjoint5
      - rightjoint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0

updown_controller:
  ros__parameters:
    joints:
      - updown
    interface_name: position

pitch_controller:
  ros__parameters:
    joints:
      - pitch
    interface_name: position

turn_controller:
  ros__parameters:
    joints:
      - turn
    interface_name: position
